version: '3.8'

services:
  apache1:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache1
    volumes:
      - ./apache/apache1.html:/usr/local/apache2/htdocs/index.html
    networks:
      - webnet

  apache2:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache2
    volumes:
      - ./apache/apache2.html:/usr/local/apache2/htdocs/index.html
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
